import benchmark as bm
import datasets as ds
import matplotlib.pyplot as plt
import numpy as np
import math
import pandas as pd

# Dataset generation
print("Generating datasets...")
dim1 = [100+50*i for i in range(0, 78)]
randomDataset = ds.generate_random_dataset(len(dim1), 2000, dim1)
dim2 = [100+10*i for i in range(0, 40)]
worstDataset = ds.generate_worst_dataset(len(dim2), 200, dim2)

# Benchmarks
print("Benchmarking first set of data...")
normalInsertionTimes, normalSearchTimes = bm.benchmark(randomDataset, "normal")
print("Benchmarking second set of data...")
booleanInsertionTimes, booleanSearchTimes = bm.benchmark(randomDataset, "boolean")
print("Benchmarking third set of data...")
listInsertionTimes, listSearchTimes = bm.benchmark(randomDataset, "list")
print("Benchmarking fourth set of data...")
normalInsertionHeights, normalSearchHeights = bm.benchmark_nodes(randomDataset, "normal")
print("Benchmarking fifth set of data...")
booleanInsertionHeights, booleanSearchHeighs = bm.benchmark_nodes(randomDataset, "boolean")
print("Benchmarking sixth set of data...")
listInsertionHeights, listSearchHeights = bm.benchmark_nodes(randomDataset, "list")
print('Benchmarking seveth set of data...')
worstNormalInsertionTimes, worstNormalSearchTimes = bm.benchmark(worstDataset, "normal")
print('Benchmarking eighth set of data...')
worstBooleanInsertionTimes, worstBooleanSearchTimes = bm.benchmark(worstDataset, "boolean")
print('Benchmarking nineth set of data...')
worstListInsertionTimes, worstListSearchTimes = bm.benchmark(worstDataset, "list")
print('Benchmarking tenth set of data...')
worstNormalInsertionHeights, worstNormalSearchHeights = bm.benchmark_nodes(worstDataset, "normal")
print('Benchmarking eleventh set of data...')
worstBooleanInsertionHeights, worstBooleanSearchHeights = bm.benchmark_nodes(worstDataset, "boolean")
print('Benchmarking twelveth set of data...')
worstListInsertionHeights, worstListSearchHeights = bm.benchmark_nodes(worstDataset, "list")

# Plots and tables
plt.figure(num = 1, figsize=(7, 7))
plt.plot( dim1, normalInsertionTimes, label='Normal times')
plt.plot( dim1, booleanInsertionTimes, label='Boolean times')
plt.plot( dim1, listInsertionTimes, label='List times')
plt.title('Insertion times')
plt.xlabel('Dataset dimension')
plt.ylabel('Time in ns')
plt.legend(loc="upper left")
plt.savefig('../Relazione/Resources/ABR_Resources/InsertionTimes.png')

plt.figure(num = 2, figsize=(7, 7))
plt.plot( dim1, normalInsertionHeights, label='Normal heights')
plt.plot( dim1, booleanInsertionHeights, label='Boolean heights')
plt.plot( dim1, listInsertionHeights, label='List heights')
plt.title('Insertion heights')
plt.xlabel('Dataset dimension')
plt.ylabel('Height')
plt.legend(loc="upper left")
plt.savefig('../Relazione/Resources/ABR_Resources/InsertionHeights.png')

plt.figure(num = 3, figsize=(7, 7))
plt.plot( dim1, normalSearchTimes, label='Normal times')
plt.plot( dim1, booleanSearchTimes, label='Boolean times')
plt.plot( dim1, listSearchTimes, label='List times')
plt.title('Search times')
plt.xlabel('Dataset dimension')
plt.ylabel('Time in ns')
plt.legend(loc="upper left")
plt.savefig('../Relazione/Resources/ABR_Resources/SearchTimes.png')

plt.figure(num = 4, figsize=(7, 7))
plt.plot( dim1, normalSearchHeights, label='Normal heights')
plt.plot( dim1, booleanSearchHeighs, label='Boolean heights')
plt.plot( dim1, listSearchHeights, label='List heights')
plt.title('Search heights')
plt.xlabel('Dataset dimension')
plt.ylabel('Height')
plt.legend(loc="upper left")
plt.savefig('../Relazione/Resources/ABR_Resources/SearchHeights.png')

plt.figure(num = 5, figsize=(7, 7))
plt.plot( dim2, worstNormalInsertionTimes, label='Normal times')
plt.plot( dim2, worstBooleanInsertionTimes, label='Boolean times')
plt.plot( dim2, worstListInsertionTimes, label='List times')
plt.title('Insertion times')
plt.xlabel('Dataset dimension')
plt.ylabel('Time in ns')
plt.legend(loc="upper left")
plt.savefig('../Relazione/Resources/ABR_Resources/WorstInsertionTimes.png')

plt.figure(num = 6, figsize=(7, 7))
plt.plot( dim2, worstNormalInsertionHeights, label='Normal heights')
plt.plot( dim2, worstBooleanInsertionHeights, label='Boolean heights')
plt.plot( dim2, worstListInsertionHeights, label='List heights')
plt.title('Insertion heights')
plt.xlabel('Dataset dimension')
plt.ylabel('Height')
plt.legend(loc="upper left")
plt.savefig('../Relazione/Resources/ABR_Resources/WorstInsertionHeights.png')

plt.figure(num = 7, figsize=(7, 7))
plt.plot( dim2, worstNormalSearchTimes, label='Normal times')
plt.plot( dim2, worstBooleanSearchTimes, label='Boolean times')
plt.plot( dim2, worstListSearchTimes, label='List times')
plt.title('Search times')
plt.xlabel('Dataset dimension')
plt.ylabel('Time in ns')
plt.legend(loc="upper left")
plt.savefig('../Relazione/Resources/ABR_Resources/WorstSearchTimes.png')

plt.figure(num = 8, figsize=(7, 7))
plt.plot( dim2, worstNormalSearchHeights, label='Normal heights')
plt.plot( dim2, worstBooleanSearchHeights, label='Boolean heights')
plt.plot( dim2, worstListSearchHeights, label='List heights')
plt.title('Search heights')
plt.xlabel('Dataset dimension')
plt.ylabel('Height')
plt.legend(loc="upper left")
plt.savefig('../Relazione/Resources/ABR_Resources/WorstSearchHeights.png')
